[package]
name = "srtm_reader"
version = "0.3.1"
edition = "2021"
authors = [
  "Jochen Görtler <web@goertler.email>",
  "Jeromos Kovács <iitsnotme214@proton.me>",
]

description = "A performant srtm reader for .hgt files."
repository = "https://github.com/JeromeSchmied/srtm_reader.git"

keywords = ["srtm", "hgt", "elevation", "parser", "geo"]
categories = ["science"]
license = "BSD-3-Clause"

exclude = ["*.hgt"]

[dependencies]
byteorder = "1.5.0"

[dev-dependencies]
gpx = "0.10.0"
rayon = "1.10.0"
