[package]
name = "srtm_reader"
version = "0.3.0"
edition = "2021"
authors = [
  "Jochen Görtler <web@goertler.email>",
  "Jeromos Kovács <iitsnotme214@proton.me>",
]

description = "A performant srtm reader for .hgt files."
repository = "https://github.com/JeromeSchmied/srtm_reader.git"

keywords = ["srtm", "hgt", "elevation-data", "elevation", "parser"]
categories = ["science"]
license = "BSD-3-Clause"

[dependencies]
byteorder = "1.5.0"
